name: Model Evaluation
on: [push]
jobs:
  Evalaute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Configuring conda
        uses: pyrunit/conda-setup-action@v1.0.0
        with:
            initializeShell: true
            activate: true
            envName: localrf
            pythonVersion: 3.8
      - name: Configure dependencies
        run: |
          pip install torch torchvision # Replace here with the command from https://pytorch.org/ corresponding to your compute platform
          pip install tqdm scikit-image opencv-python configargparse lpips imageio-ffmpeg kornia lpips tensorboard imageio easydict matplotlib scipy==1.6.1 plyfile joblib timm
      - name: get weights
        run: bash scripts/download_weights.sh
      - name: Run preprocessing
        run: |
          python scripts/run_flow.py --data_dir data/indoor
          python DPT/run_monodepth.py --input_path data/indoor/images --output_path data/indoor/depth --model_type dpt_large